# Generated by Django 2.2.6 on 2019-12-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191205_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
