# Generated by Django 2.2.6 on 2019-10-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanskritLessons',
            fields=[
                ('lesson_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=20)),
            ],
        ),
    ]
