# Generated by Django 2.2.6 on 2020-02-26 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SanskritLessons',
            fields=[
                ('lesson_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('q_number', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SanskritQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('answer', models.CharField(default='', max_length=50)),
                ('q_type', models.CharField(choices=[('t', 'typing'), ('s', 'select'), ('j', 'jump')], max_length=10)),
                ('key_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanskrit.SanskritLessons')),
            ],
        ),
        migrations.CreateModel(
            name='SanskritAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_choice', models.CharField(max_length=50)),
                ('ans_image', models.ImageField(default='design.png', upload_to='pics/')),
                ('key_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanskrit.SanskritQuestions')),
            ],
        ),
    ]
