# Generated by Django 2.2.6 on 2019-10-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanskritlessons',
            name='question',
        ),
        migrations.CreateModel(
            name='SanskritQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanskrit.SanskritLessons')),
            ],
        ),
    ]
