# Generated by Django 2.2.6 on 2020-02-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanskritlessons',
            name='user_key',
        ),
    ]
