# Generated by Django 2.2.6 on 2019-10-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0002_auto_20191020_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanskritquestions',
            old_name='key',
            new_name='key_question',
        ),
        migrations.CreateModel(
            name='SanskritAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=50)),
                ('key_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanskrit.SanskritQuestions')),
            ],
        ),
    ]
