# Generated by Django 2.2.6 on 2020-02-26 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanskrit', '0002_remove_sanskritlessons_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanskritlessons',
            name='user_key',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
