# Generated by Django 2.2.6 on 2020-02-26 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanskrit', '0003_sanskritlessons_user_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanskritlessons',
            name='user_key',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_key', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sanskrit.SanskritLessons')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
