# Generated by Django 2.2.6 on 2019-10-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0003_auto_20191021_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanskritquestions',
            name='answer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='SanskritAnswers',
        ),
    ]
