# Generated by Django 2.2.6 on 2020-02-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0004_auto_20200227_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanskritlessons',
            name='completed',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
