# Generated by Django 2.2.6 on 2019-11-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0004_auto_20191021_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanskritquestions',
            name='q_jump',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sanskritquestions',
            name='q_select',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sanskritquestions',
            name='q_type',
            field=models.BooleanField(default=False),
        ),
    ]
