# Generated by Django 2.2.6 on 2019-11-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0005_auto_20191128_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanskritquestions',
            old_name='q_type',
            new_name='q_typing',
        ),
    ]
