# Generated by Django 2.2.6 on 2019-11-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0006_auto_20191128_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanskritquestions',
            name='q_jump',
        ),
        migrations.RemoveField(
            model_name='sanskritquestions',
            name='q_select',
        ),
        migrations.RemoveField(
            model_name='sanskritquestions',
            name='q_typing',
        ),
        migrations.AddField(
            model_name='sanskritquestions',
            name='q_type',
            field=models.CharField(choices=[('t', 'typing'), ('s', 'select'), ('j', 'jump')], default=False, max_length=10),
        ),
    ]
