# Generated by Django 2.2.6 on 2020-02-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0006_auto_20200227_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='completed',
        ),
        migrations.AddField(
            model_name='sanskritlessons',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
