# Generated by Django 2.2.6 on 2019-11-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0007_auto_20191201_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanskritquestions',
            name='q_type',
            field=models.CharField(choices=[('t', 'typing'), ('s', 'select'), ('j', 'jump')], max_length=10),
        ),
    ]
