# Generated by Django 2.2.6 on 2019-12-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0008_auto_20191201_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanskritAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_choice', models.CharField(max_length=50)),
                ('ans_image', models.ImageField(default='design.png', upload_to='static\\pics')),
                ('key_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanskrit.SanskritQuestions')),
            ],
        ),
    ]
