# Generated by Django 2.2.6 on 2019-12-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0009_sanskritanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanskritanswers',
            name='ans_image',
            field=models.ImageField(default='design.png', upload_to='pics/'),
        ),
    ]
