# Generated by Django 2.2.6 on 2020-02-27 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0009_auto_20200227_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lesson_key',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sanskrit.SanskritLessons'),
        ),
    ]
