# Generated by Django 2.2.6 on 2020-03-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0012_auto_20200229_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
