# Generated by Django 2.2.6 on 2020-03-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0013_audio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanskritlessons',
            name='lessons_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
