# Generated by Django 2.2.6 on 2020-03-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0016_auto_20200310_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='design.png', upload_to='pics/'),
        ),
    ]
