# Generated by Django 2.2.6 on 2020-03-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0018_auto_20200326_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
