# Generated by Django 2.2.6 on 2020-03-28 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0019_userprogress_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
