# Generated by Django 3.2.4 on 2021-06-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0020_auto_20200328_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanskritquestions',
            name='q_number',
            field=models.IntegerField(default=0),
        ),
    ]
